name: Status Bar Lyric - auto

on:
  schedule:
    - cron: '*/15 * * * *'  # 每 15 分钟执行一次

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.get_update.outputs.result }}
      ORIGIN_URL: ${{ steps.get_update.outputs.ORIGIN_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
      - name: 检测更新
        id: get_update
        run: |
          ORIGIN_URL=$(curl ${{ secrets.API }})
          echo "ORIGIN_URL=$ORIGIN_URL" >> $GITHUB_OUTPUT
          new_version=$(echo $ORIGIN_URL | cut -d"/" -f4)
          previous_version=$(jq -r .version $GITHUB_WORKSPACE/update.json)
          echo "$new_version"
          echo "$previous_version"
          if [[ "$new_version" != "$previous_version" ]]; then
            echo "检测到新版本: $new_version"
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "已是最新版本: $previous_version"
            echo "result=false" >> $GITHUB_OUTPUT
          fi
  status_bar_lyric:
    if: needs.check-version.outputs.result == 'true'
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: 开始构建
        run: |
          ORIGIN_URL="${{ needs.check-version.outputs.ORIGIN_URL }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/zjw2017/statusbarlyric-build/actions/workflows/build%20-%20artificial.yml/dispatches \
            -d '{"ref":"main","inputs":{"ORIGIN_URL":"'"${ORIGIN_URL}"'"}}'
